acheong08/ChatGPT

- src/revChatGPT/__main__.py
- src/revChatGPT/revChatGPT.py
As the response streams in from ChatGPT, print each line as soon as it is fully received, wrapping at 80 characters. (TODO: make that wrap automatically based on terminal width.)
> Print response as it streams

- src/revChatGPT/__main__.py
Code blocks in output were being messed up by ignoring newlines when line-wrapping. This fixes that to properly honor newlines in the streamed output when wrapping.
> properly wrap output for preexisting newlines when streaming

- src/revChatGPT/revChatGPT.py
It seems something has changed to make the error handler ignores HTML error response in the latest version.
> Fix html error respond ignored in handler

- .github/workflows/codeql.yml
- .github/workflows/pylint.yml
- .github/workflows/python-package.yml
- .github/workflows/python-publish.yml
Warnings occurred when v3 is used and all versions running v3 will result in a fail as of March 2023. So I just bumped to a latest version 4.3.0 and it works like a charm without a warnings.
> Change version of setup-python to 4.3.0

- src/asyncChatGPT/asyncChatGPT.py
- src/revChatGPT/revChatGPT.py
I think it would be a better choice to make the timeout parameter for requests a configurable property of the class itself, rather than using a hard-coded number.
> feat: make timeout configurable

- src/revChatGPT/__main__.py
- wiki/Setup.md
The [XDG Base Directory specification](https://wiki.archlinux.org/title/XDG_Base_Directory) specifies the environment variable `XDG_CONFIG_HOME` to hold the directory for user-specific configurations. Furthermore, configuration files are commonly placed under the `~/.config` directory. Hence, this PR adds support for configuration in these locations.
With this PR, the following paths are checked for configuration, in order of predence (highest to lowest) -- the first found file is used:
* `config.json` in the current directory (as before)
* `$XDG_CONFIG_HOME/revChatGPT/config.json`, if the environment variable `XDG_CONFIG_HOME` is set
* `$HOME/.config/revChatGPT/config.json`, if the environment variable `HOME` is set (in most cases it is).
> Support XDG Base Directory specification for config.json

- src/revChatGPT/__main__.py
Add termination on Ctrl-C in CLI with the message "Goodbye!" instead of a long traceback.
> Add termination on Ctrl-C in CLI without a long traceback

- src/revChatGPT/revChatGPT.py
Trailing whitespace raises a httpx.LocalProtocolError https://github.com/encode/httpx/issues/1640 in refresh_session()
`httpx.LocalProtocolError: Illegal header value b'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15 '`
Removing the space should fix the issue.
> Fix httpx LocalProtocolError

- .github/workflows/python-package.yml
Instead of mapping env vars inline it could be done via `env`
See: https://docs.github.com/en/actions/learn-github-actions/environment-variables
Not sure the tests should depend on Network though :/ feels like it will end up with flaky tests.
Did you consider something like https://vcrpy.readthedocs.io/en/latest/index.html?
> Make pytest env var more readable

- src/revChatGPT/revChatGPT.py
The issue in #311 happed because the previous code use none-async function `refresh_session()` wich contain `asyncio.run()` into async function `get_chat_response()`, this cause nested use of asyncio.run
Here is temporary solution to fix
> temporary solution for async in effective way

- src/revChatGPT/ChatGPT.py
Currently change_title() doesn't work and raise this exception. You forgot to quote the title in JSON data.
> Exception: ('Response code error: ', 422)
> fix: send valid JSON data in change_title()

- src/revChatGPT/ChatGPT.py
Hey,
Tiny PR which will allow retry libraries to catch a specific exception type when hitting e.g. rate limit and direct their behavior accordingly. On main it was just raising a bare `Exception`.
> change raised exception type to HTTPError when response code != 200

- src/revChatGPT/Official.py
Allows to pass a custom user name to be provided for the own prompts to all methods of the `ChatBot`. Currently not usable from the command line, I'm not really sure how that would be helpful there...
It is helpful for things like Discord bots though, allowing ChatGPT to differentiate between users and responding in a custom way to each one individually.
Also fixes the recursion of `construct_prompt` not taking the `custom_history` parameter.
> Add customizable user

- src/revChatGPT/Official.py
rstrip removes the characters from the end of strings until the last character is not present in the set of characters(string) that we send as an argument, as in this case `<|im_end|>`. so after removing this, if our string still has 'i' or 'e' or 'm' etc. at the end. it will also removes that. So, instead we can use `removesuffix` in Python 3.9+. 
In my case i have an 'e' at the end and it is removing every time.  After wasting so much time, i found that. 😂
I found this here: https://stackoverflow.com/questions/46222645/string-rstrip-is-removing-extra-characters
> Change `rstrip` to `removesuffix`

- src/revChatGPT/V2.py
#670 
使proxy应用于httpx stream,防止出现当无法访问[https://chat.duti.tech]时,获取access_token成功但ask请求失败的情况(ssl.SSLSyscallError](https://chat.duti.xn--tech%2Caccess_tokenask%28ssl-so19bd13bevg8xkf79bu33c2pjbl9a0y2ceqzett9ej80c3dk.sslsyscallerror/): Some I/O error occurred (_ssl.c:1131))
> 修复issues#670问题 

- setup.py
- src/revChatGPT/V2.py
When running with insecure I got the following error:
```
self.api_key = response.json()["accessToken"]
KeyError: 'accessToken'
```
I was able to fix this by using the requests library instead of httpx to send a POST request:
```python
import requests
...
auth_request = requests.post(PROXY_URL + "/auth", json={"email": email, "password": password})
self.api_key = auth_request.json()["accessToken"]
```
> Fix KeyError: 'accessToken'

- src/revChatGPT/V1.py
We need to reset the `self.parent_id` to `None` when calling `ask` with `conversation_id`, or else the `conversation_id` and `parent_id` will mismatch in the following request, causing the request to fail
> Resetting parent_id when switching to a new conversation_id

- src/revChatGPT/V1.py
My bad for the non-specific error handling, I dived into the OpenAPI.auth to see if there was any logic to handling the wrong username and pass but didn't see anything. By default, it would just return "Wrong status code" since I guess a wrong username and password don't change the status code received. 
**Before** 
**After**
> error handling wrong user and pass

- src/revChatGPT/V1.py
It seems to me that 360 is too long as a timeout in some situations (for example, for a periodic check of the answer).
Therefore, it makes sense to add timeout as a parameter to the ask function `ask(..., timeout=)`
> Add timeout parameter to ask()

- src/revChatGPT/V1.py
Fixes the !setconversation command and adds it to the displayed documentation.
> fix conversation ID command 

- src/revChatGPT/V1.py
Now, instead of an exception, it just prints text to the console (for example: `{'detail': 'Too many requests in 1 hour. Try again later.'}`). Therefore, it cannot be caught.
Adding an exception will make it possible to catch this error.
> Add exception when "Field missing"

- src/revChatGPT/V1.py
Due to character encoding issues causing garbled text in the API response for Chinese characters, an optional parameter has been added to allow specifying the character encoding when calling the API.
**As-Is**
`chatbot.get_msg_history(convo_id)`
'content': {'content_type': 'text', 'parts': ['ä½\xa0ç\x9a\x84å\x90\x8då\xad\x97']},
**To-Be**
`chatbot.get_msg_history(convo_id,"utf-8")`
'content': {'content_type': 'text', 'parts': ['我的名字是ChatGPT。']},
> Fix garbled text in get_msg_history API response.

- src/revChatGPT/V1.py
- wiki/V1.md
Fix encoding issues in __check_response to detect encoding during runtime. This fix will solve the Chinese garbled characters issue in get_conversations method permanently.
Also, fixed the encoding problem in change_title method, which prevented requests from being made when passing Chinese characters.
> fixed the encoding problem in change_title method

- src/revChatGPT/V1.py
From what I'm seeing today, this type of error's response body is like 
```shell
{'detail': 'Too many requests in 1 hour. Try again later.'}
```
the key is detail not details
> Fix rate limit exceeded handling

- src/revChatGPT/V1.py
Seems `httpx` could just properly deal with back-slashes, unescaping would break the JSON (the issue was observed at [here](https://github.com/n3d1117/chatgpt-telegram-bot/pull/31)).
> Avoid unnecessary unescaping for httpx

- src/revChatGPT/V1.py
I got so many conversations under my account, everytime the server is restarted, `self.__map_conversations()` is called to create the mapping, which takes quite a long time to finish. This newly introduced options `lazy_loading` can help only load the mapping of single conversation when it's not loaded before.
> Support lazy loading of history conversations

- src/revChatGPT/V1.py
When the `self.cache_path` is in the current working directory (like when the HOME env does not exist on win10), `osp.dirname(self.cache_path)` returns an empty string. Then, the call to `os.makedirs("", exist_ok=True)` crashes. This changes the call to be `os.makedirs(".", exist_ok=True)`, which seems to fix the issue.
> Fix cache dir bug

- src/revChatGPT/V1.py
Close: #947 
When $HOME is None, the value of cache_path is .chatgpt_cache.json. In this case, `osp.dirname(cache_path)` returns an empty value, and running `os.mkdir(osp.dirname(cache_path))` will result in an error
If $HOME is None, set the value of cache_path to the value obtained by using `osp.join(os.getcwd(),".chatgpt_cache.json")`.
> repair cant create cache_dir when $HOME is None ref:#947

- src/revChatGPT/V1.py
Problem: Currently getting a false "Field missing" error because the Chatbot.ask method does not handle "invalid_token" response codes from api/conversation.
Solution: This PR adds code to handle "invalid_token" response codes to accurately warn users when they provide an invalid bearer access token instead of just raising "Field missing" (which is also inaccurate because the field is not missing).
Related issue: https://github.com/acheong08/ChatGPT/issues/955
> Raise an error for invalid_token

- src/revChatGPT/V1.py
Currently parameters of the Error class being passed incorrectly when an error occurs in some methods.
In this PR, keywords are explicitly specified and delivered to all error generating codes for which keywords are not specified.
> Fix wrong parameters passed in some errors

- src/revChatGPT/V3.py
Add a condition during initialization to prevent the `system_prompt` token from exceeding `max_tokens`, to avoid infinite looping during truncation. Additionally, use `pop` in truncation to avoid losing `system_prompt`.
> Fix truncation loop

- .gitignore
- README.md
- src/revChatGPT/V3.py
I added the ability for people to add a config file using --config. There are some conflicts with a few new commits, so I still need to resolve them. Link this pr to issue #981.
> Added the ability for users to use config files with V3

- src/revChatGPT/utils.py
This version includes the following changes:
print_formatted_text is used instead of print to print the prompt text with styling information. The key_bindings parameter is now optional for get_input, since it is not always needed. The prompt_text parameter is added to get_input, which allows the caller to specify the text to be displayed as the prompt. If session is None, prompt_text is printed with print_formatted_text before calling input(). prompt_continuation is set to an empty string to suppress the default continuation prompt ("> "). The prompt_kwargs dictionary is used to specify the style of the prompt text, which is set to "class:prompt" to match the default prompt style of prompt_toolkit.
> Improved version

- src/revChatGPT/V0.py
API type 0 stops working with this error:
```
C:\Users\...>C:\Users\...\AppData\Local\Programs\Python\Python310\python -m revChatGPT.V0 -h
Traceback (most recent call last):
File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
exec(code, run_globals)
File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V0.py", line 9, in <module>
from typing import LiteralString
ImportError: cannot import name 'LiteralString' from 'typing' (C:\Users\...\AppData\Local\Programs\Python\Python310\lib\typing.py)
```
Removing return type `LiteralString` fixes it. And I also can't find …
> Remove LiteralString

- src/revChatGPT/V0.py
If you use V0 and, for example, dalle (calling the `openai` library both there and there), then the `api_key` in V0 may become `None`.
Therefore, it is better to re-assign it each time. The same goes for proxies.
So, instead of initializing them at the `__init__`
```python
openai.api_key = api_key or os.environ.get("OPENAI_API_KEY")
openai.proxy = proxy or os.environ.get("OPENAI_API_PROXY")
```
It's better to save them as class variables
```python
self.api_key = api_key or os.environ.get("OPENAI_API_KEY")
self.proxy = proxy or os.environ.get("OPENAI_API_PROXY")
```
And then, re-assign each time before using `openai.Completion.create` or `openai.Completion.acreate`
```python
openai.api_key = self.api_key
openai.proxy = self.proxy
```
> Update openai.api_key and openai.proxy every completion

- src/revChatGPT/utils.py
`set[str]` is not supported in old python version(before 3.10):
```python
def get_filtered_keys_from_object(obj: object, *keys: str) -> set[str]:
TypeError: 'type' object is not subscriptable
```
so it's recommended to use `typing` module  annotate types instead the class `set`
> [refactor] using typing modules.

- src/revChatGPT/V1.py
Sometimes it's inconvenient to set `CHATGPT_BASE_URL` in environment variables, especially for those who use self-hosted V4 proxy. It will be great if we can set base_url in config.
> Support set base_url in V1 config

- setup.py
- src/revChatGPT/V1.py
- src/revChatGPT/V3.py
During my use, I selected the `TEXT-DAVINCI-003` model, 
But it always returns `Unsupported engine {self.engine}`, I think he should return Unsupported engine TEXT-DAVINCI-003 is correct.
I think this should be a bug.
> fix: Unsupported engine error not displayed correctly

- docs/README.md
- docs/README_ja.md
- docs/README_zh.md
I created Japanese translated README.
> Add Japanese README

- src/revChatGPT/V1.py
Been playing around with this to avoid using the GO proxy method for TLS spoofing. It uses `curl-cffi` module to spoof the TLS fingerprint (I set chrome110). But, since that module doesn't support stream=True on requests, a workaround is to write `content_callback` to a temp file, then read from it, then delete. For async it is the same principle, just uses AsyncSession instead. 
Works well enough from my various tests, but can never be 100% sure. For example, the following outputs every task result correctly with no parts missing or any weirdness like that.
```py
import asyncio
import sys
from revChatGPT.V1 import Chatbot, AsyncChatbot
from const import access_token, conversation_id
if sys.version_info >= (3, 8) and sys.platform.lower().startswith("win"): …
```
> Experimental pure Python Cloudflare bypass

- setup.py
- src/revChatGPT/V3.py
I believe you missed two of the newly added models released by OpenAI on 06/13:
"gpt-3.5-turbo-16k-0613"
"gpt-4-32k-0613"
> [6.3.2] Support for all 0613 models

- src/revChatGPT/V3.py
I am facing the following error while call the V3 ask API with model `gpt-4-0613`. 
(Note: the status_code is 200)
The `ask_stream_async` will not raise any errors correctly, instead it will continue to add an entry `{"role": "", "content": ""}`  to the conversation history, which will block **all** conversation after that error API call:
> [Bug] Error has not been raised correctly in V3 if server facing issues while processing api

- src/revChatGPT/V1.py
the auth method was renamed to get_access_token in version 2.0 of OpenAIAuth
> update the V1 get access token  because OpenAIAuth update to 2.0.0

- src/revChatGPT/V3.py
Hello, I am having an issue with support for Azure API on issue #1342. The original version does not seem to be working. To solve this issue, I have updated the function `ask_stream` based on the Azure office introduction.
Now, users can use Azure chatgpt API by adding ```API_URL="your Endpoint" MODEL_NAME="your deployment name"```.
The Azure office introduction: https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?tabs=command-line&pivots=rest-api
> Update Azure API

- src/revChatGPT/V1.py
- src/revChatGPT/V3.py
- src/revChatGPT/version.py
Reverts acheong08/ChatGPT#1458
> Revert "fix for crashes in tiktoken due to message being empty and not being …"

- src/revChatGPT/V1.py
The new openai response message contain a message without "message", so just continue to fix the whole programe exit.
> Fix the response check error based the new opanai response
