- src/revChatGPT/revChatGPT.py
To let the library user handle exceptions themselves
> Raise exceptions instead of returning

- src/revChatGPT/revChatGPT.py
I managed to modify the error handler in the function `get_chat_text`.
It should be able to raise error with message for HTML (when the site is down or blocked) and for regular json responses, which is handy for chat bot development.
I cannot test for all possible errors so far. Please let me know if there are any problems with this PR.
> Error handling for get_chat_text

- README.md
Add a PyPI badges to the Readme to be able to quickly see what the latest version published to PyPI is and the number of monthly downloads.
> Add PyPI badges to Readme

- src/revChatGPT/revChatGPT.py
> fix some pylint problems caused by unnecessary "else"

- src/revChatGPT/revChatGPT.py
Updated the ValueError text from get_chat_response to match the possible options
> Updated ValueError output text

- src/revChatGPT/__main__.py
Script does not check if config.json exists before entering the main loop
> Exit program if config.json does not exist

- src/revChatGPT/revChatGPT.py
This removes the dependency of bs4 and replaces it with regex equivalents. I've tested it all as working but this may be more prone to breaking if things update.
> Remove usage of bs4

- .github/workflows/codeql.yml
Introducing [CodeQL](https://codeql.github.com/).
> Introducing CodeQL

- setup.py
- src/revChatGPT/revChatGPT.py
> Revert "Use httpx for links instead of requests"

- src/asyncChatGPT/asyncChatGPT.py
- src/revChatGPT/revChatGPT.py
I simplified and improved the logic of functions in both `revChatGPT.py` and `asyncChatGPT.py`.
Please let me know if you think the change is too radical.
> Streamlined some parts of code

- wiki/Developer-Docs.md
change name method from get_res() to printMessage().
> fix streaming response

- src/asyncChatGPT/asyncChatGPT.py
sync the change in [Better error handling](https://github.com/acheong08/ChatGPT/commit/51245ab0fb5b31476767f17bf19992fabb7fa1f0 ) , [Check for expired session tokens](https://github.com/acheong08/ChatGPT/commit/40c6f547f8345991054ee574a2a5d48b95cd877f) to asyncChatGPT
> sync to main

- src/revChatGPT/revChatGPT.py
All the class name follow [pep-8](https://peps.python.org/pep-0008/#class-names), ChatBot AsyncChatBot
increases maintainability.
flaw:
__get_chat_text revert to earlier versions
the ChatBot get_chat_response( prompt, output="stream")return list, not a generator
> Refactor the code, change a lot

- src/revChatGPT/__main__.py
- src/revChatGPT/revChatGPT.py
added queue to support rollback more than once. Below is a real test using CLI.
---
You:
what's the rule of the game?
Chatbot:
In this particular game, the rule is simple: whenever you enter the letter "c," I will add 1 to the output number. This continues until one of us decides to stop the game. The output number starts at 0 and increases by 1 each time you enter the letter "c."
Here is an example of how the game might go:
You: c
Me: 0
You: c
Me: 1
You: c
Me: 2
You: c
Me: 3
You: c
Me: 4
You: c
Me: 5
Etc. The game continues in this way until one of us decides to stop. Let me know if you have any other questions or if you would like to play a different game.
You:
c
Chatbot:
Sure, here is the updated output number:
You: c
Me: 0
Since you entered the letter "c," I will add 1 to the output …
> added rollback queue to support multiple rollbacks. e.g. !rollback 3

- setup.py
- src/revChatGPT/revChatGPT.py
automatically use solution in #248
> Temporary solution for runing in jupyter

- wiki/Setup.md
new to github, practicing pull requests, ill try to contribute more later
> a tiny change

- setup.py
- src/revChatGPT/revChatGPT.py
- wiki/Setup.md
> rollbackfix 

- README.md
> Fix Chinese

- src/revChatGPT/ChatGPT.py
- src/revChatGPT/__main__.py
- wiki/Setup.md
I have added new configuration options that allow you to change selenium's default driver and browser with the `driver_exec_path` and `browser_exec_path` options.
I have also added the command `!setconversation` which changes the ChatGPT conversation ID and the `conversation` option in the config which sets the default conversation
I really hope to see this project grow it is awesome!
BTW sorry this had to be a seperate pull request, i'm still learning how github works
> New config options for browser selection and conversation selection

- src/revChatGPT/ChatGPT.py
- Wrapped driver functions in a try-finally block and deleted `driver.close()` since it seems to be problematic when exiting the script using Ctrl+C (KeyboardInterrupt). From testing, `driver.quit()` alone exits the Chrome processes consistently.
- Added `driver_executable_path` and `browser_executable_path` to the other driver functions so that they're synonymous.
> Fix Possible Memory Leak

- src/revChatGPT/ChatGPT.py
Added get_conversations, get_msg_history, change_title and delete_conversation
> Added Dec15 update functions

- src/revChatGPT/ChatGPT.py
Added conversation map, mapping conversation ID's to the ID of the last message
> Fixed #418

- src/revChatGPT/GPTserver.py
1. Corrected the initialisation of the Chatbot object by removing the session_token parameter that is not needed here
2. Corrected the `verif_data` function by changing the names of the required parameters to match the parameters used in the code
3. Copy the line that sets the token_available to True out of the except block so that the token is set to `true` even if an error occurs in the `/chat` endpoint
4. Add a check to see if the `session_token` field is present in the data and if the token is valid before continue executing the `/refresh` endpoint
> Add some fixes

- src/revChatGPT/Official.py
Sorry, I missed to push this change in the last PR. This will actually make it usable from the command line interface.
> Temperature as argument in command line

- src/revChatGPT/Official.py
Same as #505 for AsyncChatbot.
> Use rstrip instead of replace on async too

- src/revChatGPT/Official.py
For use from other wrappers, maybe like langchain
> Provide a variable with the name of the engine

- src/revChatGPT/Official.py
Move string constructions to own method to avoid repeating pattern
> Simplify `add_to_chat_history`

- src/revChatGPT/ChatGPT.py
The fix of [issues/559](https://github.com/acheong08/ChatGPT/issues/559), when a local variable, driver, fails in its instance create phase, the finally code-block can not handle such exception completely.   
The reproduce steps are described in [issues/559](https://github.com/acheong08/ChatGPT/issues/559).
> This is a fix of issues/559

- README.md
I updated the document to make it more clear. Thanks!
> Updated document so it is more precise.

- src/revChatGPT/Unofficial.py
Otherwise exception here:
```
while (
not self.agent_found
or not self.cf_cookie_found
or not self.puid_cookie_found
):
```
> Default self.puid_cookie_found value in __get_cf_cookies

- src/revChatGPT/V2.py
Closes: #704
See the issue for reference.
> fix: improve exception handling for status code `523`

- src/revChatGPT/V1.py
> Support session token for V1

- src/revChatGPT/V1.py
the starting checking conditions of function __login needs to be modified from "in" to "not in", or it will fail to go on.
> __login Exception conditions modification

- src/revChatGPT/V1.py
Bug: 
Once we set the `conversation_id` and `parent_id` to None again (try to initiate a new conversation) after using the chatbot to complete some conversations, it will continue to use the previous `conversation_id`. The expected behavior is to acquire a new `conversation_id`.
Fixed by modifying the logic of `conversation_id` and `parent_id` handling code.
> Fix the bug when initiating new conversations via a used chatbot

- src/revChatGPT/V1.py
Fix missing access token V2.2.7
> Fix missing access token V2.2.7

- src/revChatGPT/V1.py
After the response, we need to update the pid of the current cid at the same time
> Update the pid corresponding to cid

- src/revChatGPT/V1.py
- wiki/V1.md
"get_msg_history" interface automatically guesses the encoding if the character set parameter is not passed.
> automatically guessed

- src/revChatGPT/V1.py
Throw the error when the service is abnormal
> fix: Internal Server Error

- src/revChatGPT/V1.py
I'm thinking, get rid of verbose and use debug instead. Seem reasonable? The verbose config options is being used anyways.
I have been using this logging to see what's going on in the `Chatbot`
It includes a utility function for tracing with dumping the variables.
You can enable the logging like the following:
```python
import logging
import sys
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger().addHandler(logging.StreamHandler(sys.stdout))
```
You can add this at the top of your script where you instantiate the `Chatbot`.
I thought it would be useful for others to debug what's going on.
> Add logging remove verbose

- src/revChatGPT/V1.py
While using this lib to create other projects that using `logging` module, some log with `INFO` level outputs by this lib may mess up the console and log file.
> perf: level of some output

- src/revChatGPT/V1.py
May provide better linting, ide prompt ...
> added some type hints for function args

- src/revChatGPT/V1.py
will check access token first, if not available, use session token or username & pswd.
Tested combination of at, st, un, pswd; st, un, pswd; un, pswd. These passed without issue
> support providing more than one type of login info

- src/revChatGPT/V1.py
This is not important for single bot case, for a pool this may be useful for monitoring
> Add model name to ask return

- .gitignore
- .vscode/settings.json
- src/revChatGPT/V1.py
- add function to persist info to a cache file
- add function to save and parse access token from cache
- can handle missing cache file, missing cache dir, corrupted cache file
Note: In this implementation, access token will be used as long as it exists in the cache file. Thus we have to make sure it's valid. I'm not aware of how to do this as mentioned [here](https://github.com/acheong08/ChatGPT/discussions/886#discussioncomment-5106367) and didn't add this function.
> [Feature] cache access token

- src/revChatGPT/V1.py
I notices that AsyncChatbot produces some small errors. There were two awaits to sync methods and a missing check for empty model.
> some fixes to make AsyncChatbot work

- README.md
- setup.py
- src/revChatGPT/V1.py
- src/revChatGPT/V2.py
- src/revChatGPT/utils.py
- wiki/V1.md
This allows for more natural multi-line inputs with navigation, and users can access input history using the arrow keys. This is extremely useful for me and presumably many other users, as we often need to refine prompts from time to time to get better responses.
> Advanced multi-line input support

- src/revChatGPT/V1.py
> Error handling for prohibited concurrent query

- src/revChatGPT/V3.py
Allows for the conversation to be saved or loaded with `!save filename` and `!load filename` commands
> add saving and loading of conversations

- src/revChatGPT/V1.py
- src/revChatGPT/V2.py
- src/revChatGPT/V3.py
- src/revChatGPT/utils.py
Completion for all commands:
Only if they are typed at the beginning of the prompt:
> add command completion

- src/revChatGPT/V3.py
Add proxy support for V3 to solve the problem of inaccessibility in some regions.
> Add proxy support for V3.

- .vscode/settings.json
- setup.py
- src/revChatGPT/Unofficial.py
- src/revChatGPT/V0.py
- src/revChatGPT/V1.py
- src/revChatGPT/V2.py
- src/revChatGPT/V3.py
- src/revChatGPT/utils.py
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18jRSjpZy4Z17i5KEENIccPIO3XDBLvdUU%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=KwDLxVF)
Several improvements to make the code more Pythonic. Few of these include:-
- Use of f-strings everywhere instead of string concatenation
- Merging several if conditionals and usage of if expressions instead of complicated nested structures
- Replacing  == with `is` wherever applicable
- Inline returns from a function
- Overall, better readable and maintainable code structure.
> Codebase Refactor

- src/revChatGPT/V1.py
if `access_token` is invalid, line detail may be a `dict` type.
> fix: line data parse fail

- src/revChatGPT/V3.py
Adds commands to control and view the bots configuration.
Also improves readability of command handler function.
> enhance bot configurability and command handling

- setup.py
- I separated the setup() function parameters into different lines for better readability. 
- I reordered the parameters so that the most important ones come first. I removed unnecessary whitespace.
- I added a docstring at the beginning to explain what the code does. 
- I removed the description parameter in favor of long_description and long_description_content_type to provide a more detailed description of the package. 
- I removed the quotes around the package names in py_modules. 
- I removed the comments since the code is self-explanatory.
> Code with some minor tweaks to make it more professional:

- src/revChatGPT/V3.py
- wiki/V3.md
Save specified conversation ids to a JSON file:
```
!save chat.json default search 
```
Load specified conversations to the current bot:
```
!load chat.json search
```
> implement multi-conversation save and load

- src/revChatGPT/V3.py
- src/revChatGPT/config/enable_internet.json
- Clean up V3 main by moving conversation state to config JSON file.
- Fix `--enable_internet` flag format
> add config files for conversation state

- setup.py
- src/revChatGPT/V3.py
The problem was that the JSON file was not being packaged into build folder.
To fix this, we include `package_data` parameter and use `find_namespace_packages` in setup.py
> fix config json file not being included in build

- src/revChatGPT/V3.py
- wiki/V3.md
- More accurate calculation of tokens used in the conversation.
- Improved `print_config()` to include tokens used and cost
> fix conversation token count

- src/revChatGPT/V3.py
- wiki/V3.md
Move print and command handler functions to CLI Chatbot class.
- Reduce unnecessary Chatbot functions
- Separation of concerns
> separate cli exclusive functionality

- src/revChatGPT/V1.py
fix a small bug
**ValueError: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "http", use "http://"**
thanks [acheong08](https://github.com/acheong08) create this project
> Fixbug: AsyncClient session proxy format error.

- src/revChatGPT/V3.py
Move global ENGINE variable to a class variable, since the engine is constrained to each individual Chatbot
> format engine variable

- src/revChatGPT/V3.py
Use max token enforcement with additional checks
> re-add max tokens enforcement

- README.md
- src/revChatGPT/V3.py
- src/revChatGPT/utils.py
Addresses #1008 by allowing custom key binding for the submit key, via `--submit_key` flag
> Submit key binding

- src/revChatGPT/utils.py
Reverts acheong08/ChatGPT#1104
> Revert "Improved version"

- wiki/Code-examples.md
**another code example for the wiki**
I hope you like it : )
> Adding a GUI code example to the wiki

- README.md
- src/revChatGPT/V3.py
- src/revChatGPT/config/enable_internet.json
- src/revChatGPT/utils.py
- wiki/V3.md
- refactor save and load functions to be used for config parsing
- include examples in `!help` command for `!save` and `!load`
- update cli to only require `--api_key` when there is no `--config` flag 
- update Readme to include config flag
> refactor config to work with load and save

- CODE_OF_CONDUCT.md
- requirements.txt
- src/revChatGPT/V0.py
- src/revChatGPT/V2.py
- src/revChatGPT/V3.py
- src/revChatGPT/typing.py
- Use local typing to manage all custom exceptions
- Add CODE_OF_CONDUCT.md
- Improve the ChatbotError feature
- V2 Qualified HTTP Status Code Error Classification
> improve exception handling

- src/revChatGPT/V0.py
- src/revChatGPT/V1.py
- src/revChatGPT/V2.py
- src/revChatGPT/unfinished/WebGPT.py
- src/revChatGPT/utils.py
Adding missing types + some small QoL changes
> Add missing types across the project

- README.md
- setup.py
- src/revChatGPT/V0.py
- src/revChatGPT/V1.py
- src/revChatGPT/V3.py
- src/revChatGPT/typing.py
> even more improve exception

- Makefile
- src/revChatGPT/V0.py
- src/revChatGPT/V1.py
- src/revChatGPT/V3.py
- src/revChatGPT/typings.py
You could release a new version, thanks
> fix something

- src/revChatGPT/V0.py
- src/revChatGPT/V1.py
- changed `if variable == "" ` to `if not variable` in a few files, cause an empty string is False, you dont need to compare it
> Replacing "if something is an emty string" with "if not something"

- .vscode/settings.json
- setup.py
- src/revChatGPT/V3.py
- src/revChatGPT/utils.py
Hi, I added `ask_async` and `ask_stream_async` methods to V3 bot.
Also fixed some typing issues and replaced `requests` with `httpx` in V3. 
Since `httpx` is already a dependency, I thought it's fine to do so.
Note that in the saved `json` file, values of `session` and `proxy` keys are duplicated, I kept `session` just for compatibility.
> feat: add async methods for V3

- docs/README.md
- docs/README_zh.md
fix the Streaming examples in readme and readme_zh
> Fix examples

- src/revChatGPT/V1.py
I hope to use a different model for each conversation, so I created this PR.
> support choosing model while starting conversation instead of during bot initialization

- src/revChatGPT/V1.py
> Fixed Windows HOMEPATH

- src/revChatGPT/V1.py
This pull request updates the file V1.py with the following changes:
1. Added a new argument "auto_continue" to the "ask" function, with a default value of False.
2. Implemented the "continue_write" function, which provides the implementation of the auto_continue feature.
3. Added and clarified the usage of the _puid in V1.py. This is from V4 that the _puid may not always be necessary for users to go through our proxy server in some cases, which is beneficial for both the users and our server.
这个 pr 更新了文件 V1.py，具体如下：
1. 向 "ask" 函数添加了一个新的参数 "auto_continue"，默认值为 False。
2. 实现了 "continue_write" 函数，该函数提供了自动继续功能的实现。
3. 在 V1.py 中添加并说明了 _puid 的使用方法。它来自 V4，_puid 在某些情况下不一定对用户访问我们的代理服务器是必要的，这对于用户和我们的服务器都有好处。
> Add new feature to V1.py and clarify the usage of _puid

- src/revChatGPT/V1.py
- tests/plugin.test.py
I tried to fix the 500 error in AsyncChatbot's 'ask' function, but obviously, it didn't work...
However, I still reorganized the code and further abstracted two functions - post_messages and the private __send_request
> Refactor AsyncChatbot and Chatbot, Extract Functions

- src/revChatGPT/V1.py
- tests/plugin.test.py
I attempted to fix the ask 500 error for the AsyncChatbot, but it's clear that I didn't succeed. Nonetheless, I took the opportunity to reorganize the code and further abstracted two functions—post_messages and the private __send_request.
By the way, I fixed some tiny errors such as "auto_continue or finish...." in the AsyncChatbot.
Actually, the OpenAI Web API has many more features. The most noticeable one is plugin support, which I have already reverse-engineered and successfully executed. If these functionalities aren't encapsulated, it would require significant and sweeping changes to the data structure.
Note:
- the plugin test py file has been put into test folder already.
- the ChatGPT may stuck in an endless loop. It, however, is a test py so I didn't fix this problem.
> Fix the error of AsyncChatbot and extract functions

- .github/workflows/codeql.yml
- .github/workflows/pull-requests.yml
This reverts commit 0103072.Reverts acheong08/ChatGPT#1311
> Revert "Not necessary for all PRs"

- docs/README_zh.md
Tons of typo fixes for Chinese (Simplified)
> typo: README_zh.md

- docs/README_ko.md
> doc: update korean document

- src/revChatGPT/typings.py
> bug fix [BUG] #1407

- src/revChatGPT/V3.py
#1420  Updated to allow the use of gpt-3.5-turbo-16k
Closes #1420
> Updated to allow the use of gpt-3.5-turbo-16k

- src/revChatGPT/V1.py
> [Bug] Fix: auto_continue function does not use the same model

- src/revChatGPT/V3.py
Feat: Fix error handling for network requests.
`V3.py` did not previously handle specific exceptions related to network connectivity and timeouts with requests using the `requests` library. 
This commit introduces a try except block to catch `requests.exceptions.Timeout` and `requests.exceptions.ConnectionError` exceptions. 
`V3.py` now prints an error message, and continues through. 
This ensures that network-related errors are properly handled.
> Fix "Catching too general exception `Exception`"

- src/revChatGPT/V1.py
Is there an existing issue for this?
No
**What happened?**
```
Setting PUID (You are a Plus user!): user-f97McucxdCHMxidtechbDJOA:1688149141-R26Nho2AX8MmKVpeKwbwtEcOG%2BrFIAA%2BPskPeOLiJHQ%3D
Saved captcha image to captcha\1688149130.9994226.jpeg
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
File "C:\Users\Mohamed Al Mehairbi\Desktop\LaughExtracts\AutoBOT\test.py", line 64, in <module>
for data in chatbot.ask("Hey there!"):
File "C:\Users\Mohamed Al Mehairbi\Desktop\LaughExtracts\AutoBOT\revChatGPT\V1.py", line 721, in ask
yield from self.post_messages(
File "C:\Users\Mohamed Al Mehairbi\Desktop\LaughExtracts\AutoBOT\revChatGPT\V1.py", line 674, in post_messages
yield from self.__send_request(
File "C:\Users\Mohamed Al …
```
> Updated V1.py

- src/revChatGPT/V1.py
param name changed from email to email_address in OpenAI Auth0 class.
> Update V1.py to follow the Auth0 version change.
